consumer_token: FXXguhRgDVW3KdQoym6w
consumer_secret: Z6DdSQl3QagVmmWh8IhKnCtGwSzgwoF3cQj2dsoj4 
callback_urls:
  production: http://twitterintegration.heroku.com/twitter/auth
  development: http://dev.twipler.com:3000/mess/auth
